services:
  gitworker:
    build:
      context: ./gitworker
      dockerfile: Dockerfile
      args:
        - USERID=${UID}
        - GROUPID=${GID}
        - REMOTE_REPOSITORY_NAME=${REMOTE_REPO_NAME}
        - REMOTE_REPO_SSH_URL=${REMOTE_REPO_SSH_URL}
    ports:
      - 22:22/tcp
      - 443:443/tcp
    networks:
      - repo-net
    volumes:
      - ./gitworker/.ssh:/home/gitworker/.ssh
      - ./gitworker/repo:/home/gitworker/repo
    secrets:
      - secret_config

networks:
  repo-net:
    driver: bridge

secrets:
  secret_config:
    file: ./secret.yaml
